apiVersion: v1
kind: Secret
metadata:
  name: api-secret
type: Opaque 
data:
  connectionString: U2VydmVyPXRjcDpjYXRhbG9nLWFwcC1kYXRhYmFzZS5kYXRhYmFzZS53aW5kb3dzLm5ldCwxNDMzO0luaXRpYWwgQ2F0YWxvZz1DYXRlZ29yeURiO1BlcnNpc3QgU2VjdXJpdHkgSW5mbz1GYWxzZTtVc2VyIElEPU1lZ2FBZG1pbjtQYXNzd29yZD0xZGF0YWJhc2VQYXNzd29yZE9uQXp1cmU7TXVsdGlwbGVBY3RpdmVSZXN1bHRTZXRzPUZhbHNlO0VuY3J5cHQ9VHJ1ZTtUcnVzdFNlcnZlckNlcnRpZmljYXRlPUZhbHNlO0Nvbm5lY3Rpb24gVGltZW91dD0zMDs=